export type SnippetCategory = 'env' | 'math' | 'structure' | 'format' | 'ref';

export interface LatexSnippet {
  id: string;
  trigger: string;        // Trigger keyword for prefix search (e.g. "eq", "frac", "align")
  label: string;          // Display label shown in popover
  category: SnippetCategory;
  description: string;    // Human-friendly description
  template: string;       // String to insert
  cursorOffset?: number;  // Offset from start of insertion where cursor should land
}

export const LATEX_SNIPPETS: LatexSnippet[] = [
  // Environments
  {
    id: 'env-equation',
    trigger: 'equation',
    label: '\\begin{equation}',
    category: 'env',
    description: 'Numbered single-line display equation block',
    template: '\\begin{equation}\n  \\label{eq:label}\n  \n\\end{equation}',
    cursorOffset: 38,
  },
  {
    id: 'env-align',
    trigger: 'align',
    label: '\\begin{align}',
    category: 'env',
    description: 'Multi-line aligned mathematical equations with &',
    template: '\\begin{align}\n  \\label{eq:align_1}\n  & = \n\\end{align}',
    cursorOffset: 39,
  },
  {
    id: 'env-figure',
    trigger: 'figure',
    label: '\\begin{figure}',
    category: 'env',
    description: 'Floating figure block with caption & label',
    template: '\\begin{figure}[htbp]\n  \\centering\n  \\includegraphics[width=0.85\\columnwidth]{figure.png}\n  \\caption{Figure description}\n  \\label{fig:label}\n\\end{figure}',
    cursorOffset: 95,
  },
  {
    id: 'env-table',
    trigger: 'table',
    label: '\\begin{table}',
    category: 'env',
    description: 'Floating academic booktabs table block',
    template: '\\begin{table}[htbp]\n  \\centering\n  \\caption{Table Caption}\n  \\label{tab:label}\n  \\begin{tabular}{lcr}\n    \\hline\n    Header 1 & Header 2 & Header 3 \\\\\n    \\hline\n    val 1 & val 2 & val 3 \\\\\n    \\hline\n  \\end{tabular}\n\\end{table}',
    cursorOffset: 36,
  },
  {
    id: 'env-itemize',
    trigger: 'itemize',
    label: '\\begin{itemize}',
    category: 'env',
    description: 'Bulleted unnumbered list',
    template: '\\begin{itemize}\n  \\item \n\\end{itemize}',
    cursorOffset: 25,
  },
  {
    id: 'env-enumerate',
    trigger: 'enumerate',
    label: '\\begin{enumerate}',
    category: 'env',
    description: 'Numbered ordered list',
    template: '\\begin{enumerate}\n  \\item \n\\end{enumerate}',
    cursorOffset: 27,
  },
  {
    id: 'env-bmatrix',
    trigger: 'bmatrix',
    label: '\\begin{bmatrix}',
    category: 'env',
    description: 'Bracketed matrix [ ... ]',
    template: '\\begin{bmatrix}\n  a & b \\\\\n  c & d\n\\end{bmatrix}',
    cursorOffset: 18,
  },
  {
    id: 'env-pmatrix',
    trigger: 'pmatrix',
    label: '\\begin{pmatrix}',
    category: 'env',
    description: 'Parenthesized matrix ( ... )',
    template: '\\begin{pmatrix}\n  a & b \\\\\n  c & d\n\\end{pmatrix}',
    cursorOffset: 18,
  },
  {
    id: 'env-cases',
    trigger: 'cases',
    label: '\\begin{cases}',
    category: 'env',
    description: 'Piecewise definition cases block',
    template: '\\begin{cases}\n  expr_1, & \\text{if } x > 0, \\\\\n  expr_2, & \\text{otherwise.}\n\\end{cases}',
    cursorOffset: 16,
  },
  {
    id: 'env-proof',
    trigger: 'proof',
    label: '\\begin{proof}',
    category: 'env',
    description: 'Mathematical proof environment with Q.E.D. box',
    template: '\\begin{proof}\n  \n\\end{proof}',
    cursorOffset: 16,
  },
  {
    id: 'env-algorithm',
    trigger: 'algorithm',
    label: '\\begin{algorithm}',
    category: 'env',
    description: 'Pseudocode algorithm float block',
    template: '\\begin{algorithm}[H]\n  \\caption{Algorithm Name}\n  \\label{alg:label}\n  \\begin{algorithmic}[1]\n    \\State Initialize $x \\leftarrow 0$\n  \\end{algorithmic}\n\\end{algorithm}',
    cursorOffset: 34,
  },

  // Math Commands
  {
    id: 'math-frac',
    trigger: 'frac',
    label: '\\frac{num}{den}',
    category: 'math',
    description: 'Fraction with numerator and denominator',
    template: '\\frac{numerator}{denominator}',
    cursorOffset: 6,
  },
  {
    id: 'math-sqrt',
    trigger: 'sqrt',
    label: '\\sqrt{x}',
    category: 'math',
    description: 'Square root radical symbol',
    template: '\\sqrt{x}',
    cursorOffset: 6,
  },
  {
    id: 'math-sum',
    trigger: 'sum',
    label: '\\sum_{i=1}^{n}',
    category: 'math',
    description: 'Summation operator with lower/upper limits',
    template: '\\sum_{i=1}^{n} ',
    cursorOffset: 15,
  },
  {
    id: 'math-int',
    trigger: 'int',
    label: '\\int_{a}^{b}',
    category: 'math',
    description: 'Definite integral with lower/upper bounds',
    template: '\\int_{a}^{b} f(x)\\,dx',
    cursorOffset: 13,
  },
  {
    id: 'math-prod',
    trigger: 'prod',
    label: '\\prod_{i=1}^{n}',
    category: 'math',
    description: 'Product operator with lower/upper limits',
    template: '\\prod_{i=1}^{n} ',
    cursorOffset: 16,
  },
  {
    id: 'math-mathbf',
    trigger: 'mathbf',
    label: '\\mathbf{X}',
    category: 'math',
    description: 'Bold mathematical tensor / vector font',
    template: '\\mathbf{X}',
    cursorOffset: 8,
  },
  {
    id: 'math-mathbb',
    trigger: 'mathbb',
    label: '\\mathbb{R}',
    category: 'math',
    description: 'Blackboard bold font for sets (Real, Complex)',
    template: '\\mathbb{R}',
    cursorOffset: 8,
  },
  {
    id: 'math-mathcal',
    trigger: 'mathcal',
    label: '\\mathcal{H}',
    category: 'math',
    description: 'Calligraphic font for Hilbert space, sets',
    template: '\\mathcal{H}',
    cursorOffset: 9,
  },
  {
    id: 'math-leftright',
    trigger: 'left',
    label: '\\left( ... \\right)',
    category: 'math',
    description: 'Auto-sizing dynamic height delimiters',
    template: '\\left(  \\right)',
    cursorOffset: 7,
  },
  {
    id: 'math-alpha',
    trigger: 'alpha',
    label: '\\alpha',
    category: 'math',
    description: 'Greek letter alpha (α)',
    template: '\\alpha',
    cursorOffset: 6,
  },
  {
    id: 'math-beta',
    trigger: 'beta',
    label: '\\beta',
    category: 'math',
    description: 'Greek letter beta (β)',
    template: '\\beta',
    cursorOffset: 5,
  },
  {
    id: 'math-gamma',
    trigger: 'gamma',
    label: '\\gamma',
    category: 'math',
    description: 'Greek letter gamma (γ)',
    template: '\\gamma',
    cursorOffset: 6,
  },
  {
    id: 'math-theta',
    trigger: 'theta',
    label: '\\theta',
    category: 'math',
    description: 'Greek letter theta (θ)',
    template: '\\theta',
    cursorOffset: 6,
  },
  {
    id: 'math-lambda',
    trigger: 'lambda',
    label: '\\lambda',
    category: 'math',
    description: 'Greek letter lambda (λ)',
    template: '\\lambda',
    cursorOffset: 7,
  },
  {
    id: 'math-sigma',
    trigger: 'sigma',
    label: '\\sigma',
    category: 'math',
    description: 'Greek letter sigma (σ)',
    template: '\\sigma',
    cursorOffset: 6,
  },
  {
    id: 'math-omega',
    trigger: 'omega',
    label: '\\omega',
    category: 'math',
    description: 'Greek letter omega (ω)',
    template: '\\omega',
    cursorOffset: 6,
  },
  {
    id: 'math-partial',
    trigger: 'partial',
    label: '\\partial',
    category: 'math',
    description: 'Partial derivative symbol (∂)',
    template: '\\partial',
    cursorOffset: 8,
  },
  {
    id: 'math-infty',
    trigger: 'infty',
    label: '\\infty',
    category: 'math',
    description: 'Infinity symbol (∞)',
    template: '\\infty',
    cursorOffset: 6,
  },
  {
    id: 'math-approx',
    trigger: 'approx',
    label: '\\approx',
    category: 'math',
    description: 'Approximately equal symbol (≈)',
    template: '\\approx',
    cursorOffset: 7,
  },

  // Document Structure
  {
    id: 'sec-section',
    trigger: 'section',
    label: '\\section{Title}',
    category: 'structure',
    description: 'Level 1 document heading',
    template: '\\section{Section Title}\n\\label{sec:label}',
    cursorOffset: 9,
  },
  {
    id: 'sec-subsection',
    trigger: 'subsection',
    label: '\\subsection{Title}',
    category: 'structure',
    description: 'Level 2 document subsection heading',
    template: '\\subsection{Subsection Title}\n\\label{subsec:label}',
    cursorOffset: 12,
  },
  {
    id: 'sec-subsubsection',
    trigger: 'subsubsection',
    label: '\\subsubsection{Title}',
    category: 'structure',
    description: 'Level 3 document subsubsection heading',
    template: '\\subsubsection{Subsubsection Title}',
    cursorOffset: 15,
  },
  {
    id: 'sec-label',
    trigger: 'label',
    label: '\\label{key}',
    category: 'structure',
    description: 'Cross-referencing anchor label',
    template: '\\label{key}',
    cursorOffset: 7,
  },

  // Text Formatting
  {
    id: 'fmt-textbf',
    trigger: 'textbf',
    label: '\\textbf{text}',
    category: 'format',
    description: 'Bold text formatting',
    template: '\\textbf{text}',
    cursorOffset: 8,
  },
  {
    id: 'fmt-textit',
    trigger: 'textit',
    label: '\\textit{text}',
    category: 'format',
    description: 'Italic text formatting',
    template: '\\textit{text}',
    cursorOffset: 8,
  },
  {
    id: 'fmt-emph',
    trigger: 'emph',
    label: '\\emph{text}',
    category: 'format',
    description: 'Emphasized italic text',
    template: '\\emph{text}',
    cursorOffset: 6,
  },
  {
    id: 'fmt-texttt',
    trigger: 'texttt',
    label: '\\texttt{code}',
    category: 'format',
    description: 'Monospace typewriter font for code',
    template: '\\texttt{code}',
    cursorOffset: 8,
  },
  {
    id: 'fmt-underline',
    trigger: 'underline',
    label: '\\underline{text}',
    category: 'format',
    description: 'Underlined text formatting',
    template: '\\underline{text}',
    cursorOffset: 11,
  },
  {
    id: 'fmt-href',
    trigger: 'href',
    label: '\\href{url}{text}',
    category: 'format',
    description: 'Hyperlink to external URL',
    template: '\\href{https://example.com}{link text}',
    cursorOffset: 7,
  },
  {
    id: 'fmt-item',
    trigger: 'item',
    label: '\\item',
    category: 'format',
    description: 'New item inside list environment',
    template: '\\item ',
    cursorOffset: 6,
  },

  // Citations & Cross-references
  {
    id: 'ref-cite',
    trigger: 'cite',
    label: '\\cite{key}',
    category: 'ref',
    description: 'BibTeX bibliography citation',
    template: '\\cite{key}',
    cursorOffset: 6,
  },
  {
    id: 'ref-ref',
    trigger: 'ref',
    label: '\\ref{key}',
    category: 'ref',
    description: 'Cross-reference to section, table, or figure',
    template: '\\ref{key}',
    cursorOffset: 5,
  },
  {
    id: 'ref-eqref',
    trigger: 'eqref',
    label: '\\eqref{eq:key}',
    category: 'ref',
    description: 'Equation reference formatted with parentheses (1)',
    template: '\\eqref{eq:key}',
    cursorOffset: 7,
  },
  {
    id: 'ref-footnote',
    trigger: 'footnote',
    label: '\\footnote{text}',
    category: 'ref',
    description: 'Bottom of page footnote note',
    template: '\\footnote{Footnote text}',
    cursorOffset: 10,
  },
];

/**
 * Fast search and filtering for LaTeX snippets
 */
export function searchLatexSnippets(query: string): LatexSnippet[] {
  const clean = query.trim().toLowerCase().replace(/^\\/, '');
  if (!clean) return LATEX_SNIPPETS.slice(0, 10);

  return LATEX_SNIPPETS.filter(s => {
    return (
      s.trigger.toLowerCase().startsWith(clean) ||
      s.label.toLowerCase().includes(clean) ||
      s.description.toLowerCase().includes(clean)
    );
  }).slice(0, 8);
}
